"""drop reviews external_id rating author

Revision ID: 05ac22aebc28
Revises: c9272131c8af
Create Date: 2026-04-27 16:24:35.069191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ac22aebc28'
down_revision: Union[str, Sequence[str], None] = 'c9272131c8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_review_external_id'), table_name='reviews', postgresql_where='(external_id IS NOT NULL)')
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'author')
    op.drop_column('reviews', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('rating', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_review_external_id'), 'reviews', ['url_id', 'external_id'], unique=True, postgresql_where='(external_id IS NOT NULL)')
    # ### end Alembic commands ###
