"""add parse_runs.review_from_date

Revision ID: d1be9912e205
Revises: 70694d325cf4
Create Date: 2026-05-09 16:21:53.936489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1be9912e205'
down_revision: Union[str, Sequence[str], None] = '70694d325cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parse_runs', sa.Column('review_from_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parse_runs', 'review_from_date')
    # ### end Alembic commands ###
